"
Represent everything that can be a variable. Used for the LocalResolver and the SSA builder. Maybe I should be merged with TAssignable?


"
Trait {
	#name : 'FASTPyTCanBeVariable',
	#category : 'FAST-Python-Model-Traits',
	#package : 'FAST-Python-Model',
	#tag : 'Traits'
}

{ #category : 'meta' }
FASTPyTCanBeVariable classSide >> annotation [

	<ignoreForCoverage>
	<FMClass: #TCanBeVariable super: #Object>
	<package: #'FAST-Python-Model'>
	<generated>
]
