"
I represent the initialization of a new dictionnary in Python. Each of my children should be instances of Pair.


"
Class {
	#name : 'FASTPyDictionary',
	#superclass : 'FASTPyCollectionInitializer',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyDictionary class >> annotation [

	<FMClass: #Dictionary super: #FASTPyCollectionInitializer>
	<package: #'FAST-Python-Model'>
	<generated>
]
