"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `sliceOwner` | `FASTPyTSliceContent` | `components` | `FASTPySlice` | Slice in which I am a component (start, end or step) (If it's the case)'|



"
Class {
	#name : 'FASTPyNone',
	#superclass : 'FASTPyLiteral',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyNone class >> annotation [

	<FMClass: #None super: #FASTPyLiteral>
	<package: #'FAST-Python-Model'>
	<generated>
]
