"
## Relations
======================

### Children
| Relation | Origin | Opposite | Type | Comment |
|---|
| `initializers` | `FASTPyTCollectionInitializer` | `collectionInitializers` | `FASTTExpression` | Each initializer defines one element.|



"
Class {
	#name : 'FASTPySet',
	#superclass : 'FASTPyCollectionInitializer',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPySet class >> annotation [

	<FMClass: #Set super: #FASTPyCollectionInitializer>
	<package: #'FAST-Python-Model'>
	<generated>
]
