"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `parentType` | `FASTPyTTypeContent` | `content` | `FASTPyType` | |



"
Class {
	#name : 'FASTPyTypeParameter',
	#superclass : 'FASTPyEntity',
	#traits : 'FASTPyTTypeContent',
	#classTraits : 'FASTPyTTypeContent classTrait',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyTypeParameter class >> annotation [

	<FMClass: #TypeParameter super: #FASTPyEntity>
	<package: #'FAST-Python-Model'>
	<generated>
]
