"
I represent a continue statement to use in loops.


"
Class {
	#name : 'FASTPyContinueStatement',
	#superclass : 'FASTPyStatement',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyContinueStatement class >> annotation [

	<FMClass: #ContinueStatement super: #FASTPyStatement>
	<package: #'FAST-Python-Model'>
	<generated>
]
